# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  say-hello:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - run:
          name: Update Apt & Instal DNSUtils for dig
          command: |
            sudo apt update -yq > /dev/null
            sudo apt install -yq dnsutils net-tools tcpdump sshpass > /dev/null
#      - run:
#          name: Check IP of protected resource prior to Twingate Connecting (Should be 34.206.39.153) && Show current Timestap
#          command: |
#            date
#            dig www.kittens.com
      - run:
          name: start TCPDump
          command: |
            sudo tcpdump -nni any udp and port 53 -w run.pcap &
      - run:
          name: Install Twingate
          command: |
            sudo apt-get install ca-certificates > /dev/null
#           echo "deb [trusted=yes] https://packages.twingate.com/apt/ /" | sudo tee /etc/apt/sources.list.d/twingate.list
            echo "deb [trusted=yes] https://apt.fury.io/twingate-stg/ /" | sudo tee /etc/apt/sources.list.d/fury.list
            sudo apt-get update > /dev/null
            sudo apt-get install twingate-stg > /dev/null
            echo "ewogICJ2ZXJzaW9uIjogIjEiLAogICJuZXR3b3JrIjogInRyaXBsZWdhdGUudHdpbmdhdGUuY29tIiwKICAic2VydmljZV9hY2NvdW50X2lkIjogImJkYTdlY2MyLTQ5ZjMtNDBmNy1iZmZiLTIyY2Y0MTQ4NjVmNiIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlHSEFnRUFNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQkcwd2F3SUJBUVFnV2JOSUswTTIwc0lQSjVXb1xuZzBXbXdNbmxxZDJJY2F0SGp4bFlxa1VGNW95aFJBTkNBQVFod09EbXp2cG4xNk91Ym5JWUdOVW52TFlOelp3UlxuM0EzYmpsMkVSK2dMN2VSVTY1dmhsNGczT0p6dm42c1lVc2dvcXJETCtwWGRKdlpTVVAyQ0JPdXZcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0iLAogICJrZXlfaWQiOiAiQU5VX2Y1dS1PclFCNWFabWJvWnkyekpYU3lVNEF0em1DQmY1M3NHLWg0YyIsCiAgImV4cGlyZXNfYXQiOiAiMjAyNC0wMS0xMFQxNzo0ODozMSswMDowMCIsCiAgImxvZ2luX3BhdGgiOiAiL2FwaS92Mi9oZWFkbGVzc19ub2RlL2xvZ2luIgp9" | base64 -d | sudo twingate-stg setup --headless=-
      - run:
          name: Set Twingate Log Level to Debug
          command: |
            sudo twingate-stg config log-level debug
      - run:
          name: Start Twingate and get connection status
          command: |
            sudo twingate-stg start           
      - run:
          name: Sleep for 5s and then check Twingate status
          command: |
            sleep 5
            sudo twingate-stg status
      - run:
          name: Run Netstat and resolvectl
          command: |
            netstat -aunp
            resolvectl status
      - run:
          name: Get current timestamp and then get IP of protected resource (www.kittens.com) which should be in CGNAT Range
          command: |
            date
            dig www.kittens.com
            date
      - run:
          name: Get Twingate log output
          command: |
            sudo journalctl -u twingate-stg --no-pager | tail -n 2500    
      - run:
           name: sleep 30s and push pcap
           command: |
              sleep 30s
              sshpass -p "ThisIsAPassword!" scp ./run.pcap testftp@54.202.99.254:~/run.pcap
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
